version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      PG_DATA: var/lib/postgresql/data
      JWT_SECRET: 'pork-top-228'
      POSTGRES_URI: 'postgres://financial_manager:123@postgresql:5432/test_financial_manager'
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
  main:
    container_name: main
    build:
      context: .
    environment:
      JWT_SECRET: 'pork-top-228'
      POSTGRES_URI: 'postgres://financial_manager:123@postgresql:5432/test_financial_manager'
    volumes:
      - .:/app
    ports:
      - 5000:5000
    command: npm run start
    depends_on:
      - postgresql
    restart: always
volumes:
  db-data:
